apiVersion: database.bizmatters.io/v1alpha1
kind: DragonflyInstance
metadata:
  name: agent-executor-cache
  namespace: intelligence-deepagents
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Create cache BEFORE NATS stream
spec:
  size: medium
  storageGB: 10
# Zero-Touch Pattern:
# - Crossplane auto-generates password
# - Connection secret auto-created: agent-executor-cache-conn
