apiVersion: batch/v1
kind: Job
metadata:
  name: create-agent-execution-stream
  namespace: intelligence-deepagents
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Create stream BEFORE deployment
spec:
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nats-cli
        image: natsio/nats-box:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        command:
        - /bin/sh
        - -c
        - |
          # Create stream for input messages
          nats stream add AGENT_EXECUTION \
            --server=nats://nats.nats.svc:4222 \
            --subjects "agent.execute.*" \
            --retention limits \
            --max-msgs=-1 \
            --max-age=24h \
            --storage file \
            --replicas 1 \
            --discard old \
            --defaults || true
          
          # Create stream for output/status messages
          nats stream add AGENT_STATUS \
            --server=nats://nats.nats.svc:4222 \
            --subjects "agent.status.*" \
            --retention limits \
            --max-msgs=-1 \
            --max-age=24h \
            --storage file \
            --replicas 1 \
            --discard old \
            --defaults || true
          
          # Create consumer
          nats consumer add AGENT_EXECUTION deepagents-runtime-workers \
            --server=nats://nats.nats.svc:4222 \
            --pull \
            --deliver all \
            --max-deliver=-1 \
            --ack explicit \
            --replay instant \
            --defaults || true
